import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#e5e2e3",
        "on-surface": "#e5e2e3",
        "tertiary-fixed": "#68fcbf",
        "surface-container": "#201f20",
        "surface-container-highest": "#353436",
        "secondary-fixed": "#eaddff",
        "inverse-surface": "#e5e2e3",
        surface: "#131314",
        "primary-fixed": "#d8e2ff",
        "tertiary-container": "#01bf87",
        "surface-container-low": "#1c1b1c",
        outline: "#8d909d",
        "tertiary-fixed-dim": "#45dfa4",
        "error-container": "#93000a",
        tertiary: "#45dfa4",
        "on-secondary": "#3f018d",
        "inverse-primary": "#2b5caf",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#c3c6d3",
        "surface-variant": "#353436",
        "on-primary-fixed-variant": "#004395",
        secondary: "#d2bbff",
        "surface-container-high": "#2a2a2b",
        "surface-dim": "#131314",
        "surface-bright": "#39393a",
        "on-tertiary": "#003825",
        "inverse-on-surface": "#313031",
        "on-primary-container": "#003a83",
        "on-tertiary-fixed": "#002114",
        "primary-container": "#7ca7ff",
        "surface-tint": "#aec6ff",
        "on-secondary-container": "#c6aaff",
        background: "#131314",
        "on-tertiary-container": "#00462f",
        "on-error": "#690005",
        "outline-variant": "#434751",
        error: "#ffb4ab",
        primary: "#aec6ff",
        "surface-container-lowest": "#0e0e0f",
        "on-secondary-fixed": "#25005a",
        "on-primary": "#002e6a",
        "primary-fixed-dim": "#aec6ff",
        "secondary-container": "#582ca7",
        "on-primary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#5629a4",
        "secondary-fixed-dim": "#d2bbff",
        "on-tertiary-fixed-variant": "#005137",

        // Backward-compatible studio palette
        studio: {
          bg: "#0e0e0f",
          surface: "#131314",
          card: "#1c1b1c",
          border: "#434751",
          muted: "#8d909d",
          text: "#e5e2e3",
          highlight: "#ffffff",
          amber: "#f59e0b",
          cyan: "#38bdf8",
          emerald: "#45dfa4",
          crimson: "#ffb4ab",
        },
      },
      borderRadius: {
        DEFAULT: "1rem",
        sm: "0.5rem",
        md: "0.75rem",
        lg: "1.5rem",
        xl: "2rem",
        "2xl": "2.5rem",
        "3xl": "3rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        gutter: "1rem",
        "gutter-lg": "1.5rem",
        margin: "1rem",
        "margin-md": "1.5rem",
        "margin-lg": "2rem",
      },
      fontFamily: {
        sans: ["Geist", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        mono: ["JetBrains Mono", "Courier New", "monospace"],
        "body-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "display-hero": ["Geist", "sans-serif"],
        "code-tabular": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-xs": ["11px", { lineHeight: "16px" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.01em" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.005em" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em" }],
        "display-hero": ["44px", { lineHeight: "52px", letterSpacing: "-0.03em" }],
        "code-tabular": ["13px", { lineHeight: "20px", letterSpacing: "0em" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.06em" }],
      },
    },
  },
  plugins: [],
};

export default config;
