"""
Multi-format export engine for analytical datasets, reproducible notebooks, and reports.
Supports CSV, Parquet, Excel (.xlsx), Jupyter Notebook (.ipynb), and Executive Markdown reports.
"""

from __future__ import annotations

import io
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd
from sqlmodel import Session, select

from services.api.models import (
    ChatTurn,
    DataFrameCheckpoint,
    Session as DbSession,
    SessionFile,
)
from services.api.session_service import DATA_DIR, session_service


class ExportEngine:
    """Generates downloadable artifacts from active session state."""

    def export_dataset(
        self,
        db: Session,
        session_id: str,
        export_format: str,
    ) -> Tuple[bytes, str, str]:
        """
        Export the active DataFrame snapshot in CSV, Parquet, or Excel format.
        Returns: (file_bytes, mime_type, filename)
        """
        session_obj = session_service.get_session(db, session_id)
        if not session_obj:
            raise ValueError(f"Session '{session_id}' not found.")

        active_version = session_obj.active_dataframe_version or "df_v0"
        checkpoint = db.exec(
            select(DataFrameCheckpoint)
            .where(
                DataFrameCheckpoint.session_id == session_id,
                DataFrameCheckpoint.version_tag == active_version,
            )
        ).first()

        # Fallback to df_v0 if active version not found
        if not checkpoint:
            checkpoint = db.exec(
                select(DataFrameCheckpoint)
                .where(DataFrameCheckpoint.session_id == session_id)
                .order_by(DataFrameCheckpoint.created_at.desc())
            ).first()

        if not checkpoint:
            raise ValueError(f"No checkpoint data found for session '{session_id}'.")

        storage_path = Path(checkpoint.parquet_storage_path)
        if not storage_path.exists():
            raise FileNotFoundError(f"Underlying Parquet file not found: {storage_path}")

        df = pd.read_parquet(storage_path)
        base_title = session_obj.title.strip().replace(" ", "_").lower()
        clean_title = "".join(c for c in base_title if c.isalnum() or c in ("_", "-")) or "dataset"

        fmt = export_format.lower().strip()
        if fmt == "csv":
            content = df.to_csv(index=False).encode("utf-8")
            mime_type = "text/csv"
            filename = f"{clean_title}_{active_version}.csv"
        elif fmt == "parquet":
            buf = io.BytesIO()
            df.to_parquet(buf, index=False)
            content = buf.getvalue()
            mime_type = "application/octet-stream"
            filename = f"{clean_title}_{active_version}.parquet"
        elif fmt in ("xlsx", "excel"):
            buf = io.BytesIO()
            with pd.ExcelWriter(buf, engine="openpyxl") as writer:
                df.to_excel(writer, index=False, sheet_name="Data")
            content = buf.getvalue()
            mime_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            filename = f"{clean_title}_{active_version}.xlsx"
        else:
            raise ValueError(f"Unsupported dataset export format: '{export_format}'. Supported: csv, parquet, xlsx.")

        return content, mime_type, filename

    def export_jupyter_notebook(
        self,
        db: Session,
        session_id: str,
    ) -> Tuple[bytes, str, str]:
        """
        Generate a fully reproducible Jupyter Notebook (.ipynb) containing setup cells,
        data loader, chronological markdown explanations, python code cells, and outputs.
        """
        session_obj = session_service.get_session(db, session_id)
        if not session_obj:
            raise ValueError(f"Session '{session_id}' not found.")

        # Query all chat turns in order
        turns = db.exec(
            select(ChatTurn)
            .where(ChatTurn.session_id == session_id)
            .order_by(ChatTurn.created_at.asc())
        ).all()

        # Query initial session file
        session_file = db.exec(
            select(SessionFile)
            .where(SessionFile.session_id == session_id)
            .order_by(SessionFile.created_at.asc())
        ).first()

        cells: List[Dict[str, Any]] = []

        # 1. Header Markdown Cell
        now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        header_md = (
            f"# {session_obj.title}\n\n"
            f"**Generated by**: `data_speaker` Autonomous Conversational Data Analyst  \n"
            f"**Session ID**: `{session_id}`  \n"
            f"**Export Timestamp**: `{now_str}`  \n"
            f"**Active Version**: `{session_obj.active_dataframe_version}`  \n\n"
            "---\n"
        )
        cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": [line + "\n" for line in header_md.splitlines()],
        })

        # 2. Environment Setup Code Cell
        setup_code = (
            "# Environment Setup and Baseline Imports\n"
            "import pandas as pd\n"
            "import numpy as np\n"
            "import plotly.express as px\n"
            "import plotly.graph_objects as go\n"
            "import plotly.io as pio\n\n"
            "# Configure Plotly for JupyterLab / Notebook rendering\n"
            "pio.renderers.default = 'notebook_connected'\n"
        )
        cells.append({
            "cell_type": "code",
            "execution_count": 1,
            "metadata": {},
            "outputs": [],
            "source": [line + "\n" for line in setup_code.splitlines()],
        })

        # 3. Dataset Ingestion Cell
        if session_file:
            ingest_md = f"### Dataset Ingestion: `{session_file.filename}`"
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [line + "\n" for line in ingest_md.splitlines()],
            })

            data_code = (
                f"# Load original dataset\n"
                f"# Original file: {session_file.filename}\n"
                f"df = pd.read_parquet('df_v0.parquet') if False else None  # Replace with local dataset path\n"
                f"# Alternatively, load directly:\n"
                f"# df = pd.read_csv('{session_file.filename}')\n"
                f"print('Loaded dataset into df')\n"
            )
            cells.append({
                "cell_type": "code",
                "execution_count": 2,
                "metadata": {},
                "outputs": [],
                "source": [line + "\n" for line in data_code.splitlines()],
            })

        # 4. Sequential Turns
        exec_counter = 3
        for turn in turns:
            if turn.user_prompt.startswith("[Time-Travel]") or turn.user_prompt.startswith("[System Audit]"):
                cells.append({
                    "cell_type": "markdown",
                    "metadata": {},
                    "source": [f"> ℹ️ **Audit**: {turn.user_prompt}\n"],
                })
                continue

            # Prompt Markdown
            prompt_md = f"### Step: {turn.user_prompt}\n"
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [line + "\n" for line in prompt_md.splitlines()],
            })

            # Code Cell (if code was executed)
            if turn.generated_code:
                outputs: List[Dict[str, Any]] = []
                if turn.stdout:
                    outputs.append({
                        "name": "stdout",
                        "output_type": "stream",
                        "text": [line + "\n" for line in turn.stdout.splitlines()],
                    })

                cells.append({
                    "cell_type": "code",
                    "execution_count": exec_counter,
                    "metadata": {},
                    "outputs": outputs,
                    "source": [line + "\n" for line in turn.generated_code.splitlines()],
                })
                exec_counter += 1

        notebook_dict = {
            "cells": cells,
            "metadata": {
                "language_info": {
                    "name": "python",
                    "version": "3.11",
                },
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3",
                },
            },
            "nbformat": 4,
            "nbformat_minor": 5,
        }

        content = json.dumps(notebook_dict, indent=2).encode("utf-8")
        base_title = session_obj.title.strip().replace(" ", "_").lower()
        clean_title = "".join(c for c in base_title if c.isalnum() or c in ("_", "-")) or "analysis"
        filename = f"{clean_title}_notebook.ipynb"
        return content, "application/x-ipynb+json", filename

    def export_executive_report(
        self,
        db: Session,
        session_id: str,
    ) -> Tuple[bytes, str, str]:
        """
        Generate a Markdown Executive Summary report synthesizing the dataset profile,
        chronological operations, code executions, and final data metrics.
        """
        session_obj = session_service.get_session(db, session_id)
        if not session_obj:
            raise ValueError(f"Session '{session_id}' not found.")

        profiles = session_service.get_session_profiles(db, session_id)
        turns = db.exec(
            select(ChatTurn)
            .where(ChatTurn.session_id == session_id)
            .order_by(ChatTurn.created_at.asc())
        ).all()
        checkpoints = session_service.list_checkpoints(db, session_id)

        now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

        lines: List[str] = [
            f"# Executive Data Analysis Report: {session_obj.title}",
            "",
            f"- **Analysis Session**: `{session_id}`",
            f"- **Generated At**: `{now_str}`",
            f"- **Active Revision State**: `{session_obj.active_dataframe_version}`",
            f"- **Total Analytical Steps**: `{len(turns)}`",
            f"- **Total Checkpoints**: `{len(checkpoints)}`",
            "",
            "---",
            "",
            "## 1. Executive Summary & Dataset Architecture",
            "",
        ]

        if profiles:
            p = profiles[0]
            lines.extend([
                f"The active dataset contains **{p.row_count:,} rows** and **{p.column_count} columns**, "
                f"utilizing approximately **{p.memory_footprint_mb:.2f} MB** of memory in the analytical kernel.",
                "",
                "### Schema Architecture",
                "",
                "| Column Name | Type | Null Count | Missing % | Unique Values |",
                "| :--- | :--- | :--- | :--- | :--- |",
            ])
            for col in p.columns:
                lines.append(
                    f"| `{col.name}` | `{col.dtype}` | {col.null_count:,} | {col.null_percentage:.1f}% | {col.cardinality:,} |"
                )
            lines.append("")

        lines.extend([
            "---",
            "",
            "## 2. Analytical Methodology & Investigation Log",
            "",
        ])

        step_num = 1
        for turn in turns:
            if turn.user_prompt.startswith("[Time-Travel]") or turn.user_prompt.startswith("[System Audit]"):
                lines.extend([
                    f"> **System Event**: {turn.user_prompt}",
                    "",
                ])
                continue

            lines.extend([
                f"### Step {step_num}: {turn.user_prompt}",
                "",
            ])
            if turn.generated_code:
                lines.extend([
                    "```python",
                    turn.generated_code.strip(),
                    "```",
                    "",
                ])
            if turn.stdout:
                lines.extend([
                    "**Execution Output**:",
                    "```text",
                    turn.stdout.strip(),
                    "```",
                    "",
                ])
            step_num += 1

        lines.extend([
            "---",
            "",
            "## 3. Version History & Checkpoint Log",
            "",
            "| Version | Trigger / Operation | Rows | Columns | Created At |",
            "| :--- | :--- | :--- | :--- | :--- |",
        ])
        for chk in checkpoints:
            active_marker = " *(Active)*" if chk.is_active else ""
            lines.append(
                f"| `{chk.version_tag}`{active_marker} | {chk.operation_summary} | {chk.row_count:,} | {chk.column_count} | {chk.created_at.strftime('%Y-%m-%d %H:%M:%S')} |"
            )
        lines.append("")

        content = "\n".join(lines).encode("utf-8")
        base_title = session_obj.title.strip().replace(" ", "_").lower()
        clean_title = "".join(c for c in base_title if c.isalnum() or c in ("_", "-")) or "report"
        filename = f"{clean_title}_executive_report.md"
        return content, "text/markdown", filename

    def export_deck_presentation(
        self,
        db: Session,
        session_id: str,
        config: Optional[Any] = None,
    ) -> Tuple[bytes, str, str]:
        """
        Generate a corporate PowerPoint (.pptx) presentation deck.
        Returns: (file_bytes, mime_type, filename)
        """
        from services.api.deck_engine import deck_engine
        from services.api.models import DeckConfigRequest

        session_obj = session_service.get_session(db, session_id)
        if not session_obj:
            raise ValueError(f"Session '{session_id}' not found.")

        cfg = config or DeckConfigRequest()
        content = deck_engine.build_deck(db, session_id, cfg)
        mime_type = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
        base_title = session_obj.title.strip().replace(" ", "_").lower()
        clean_title = "".join(c for c in base_title if c.isalnum() or c in ("_", "-")) or "deck"
        filename = f"{clean_title}_presentation.pptx"
        return content, mime_type, filename

    def export_pdf_brief(
        self,
        db: Session,
        session_id: str,
        title: Optional[str] = None,
        author: Optional[str] = None,
    ) -> Tuple[bytes, str, str]:
        """
        Generate a polished executive PDF brief using ReportLab.
        Returns: (file_bytes, mime_type, filename)
        """
        from services.api.pdf_engine import pdf_engine

        session_obj = session_service.get_session(db, session_id)
        if not session_obj:
            raise ValueError(f"Session '{session_id}' not found.")

        content = pdf_engine.build_pdf_report(
            db,
            session_id,
            title=title or session_obj.title,
            author=author or "Autonomous Data Analyst",
        )
        mime_type = "application/pdf"
        base_title = session_obj.title.strip().replace(" ", "_").lower()
        clean_title = "".join(c for c in base_title if c.isalnum() or c in ("_", "-")) or "brief"
        filename = f"{clean_title}_brief.pdf"
        return content, mime_type, filename


# Global engine instance
export_engine = ExportEngine()
